### ISSUE TITLE
Chunks can't load

### ISSUE THREAD

**Issue by alexey-va** [ItemsAdder/ItemsAdderBlocksInjector#10]
I already created a thread on your forum, but now I think that is more appropriate to post about it here:
https://forum.devs.beer/d/193-blockinjector-bug

![2023-02-10_17 15 24](https://user-images.githubusercontent.com/33997837/218114440-4b0efa51-6374-48f4-b656-ce969d761161.png)

[latest.log](https://github.com/ItemsAdder/ItemsAdderBlocksInjector/files/10708234/latest.log)

**Comment by freezyXD** [comment]
Same bug, it was on 1.19.2 paper and blockinjector 0.0.7 and can be fixed with switching to 1.19.3 client version. But now I'm using the 1.19.3 paper and blockinjector 0.0.8, and getting same problem on 1.19.3 now.

**Comment by freezyXD** [comment]
> Same bug, it was on 1.19.2 paper and blockinjector 0.0.7 and can be fixed with switching to 1.19.3 client version. But now I'm using the 1.19.3 paper and blockinjector 0.0.8, and getting same problem on 1.19.3 now.

Using only 6 plugins :
ViaVersion 4.5.1
ItemsAdder 3.3.1
BlockInjector 0.0.8
Lonelibs
ProtocolLib
Iris 2.3.14

**Comment by LoneDev6** [comment]
Download the new0.0.9 release: 
https://github.com/ItemsAdder/ItemsAdderBlocksInjector/releases
