### ISSUE TITLE
Corrupted world

### ISSUE THREAD

**Issue by FewerElk** [ItemsAdder/ItemsAdderBlocksInjector#17]
Hello, we installed Itemsadder some weeks ago, and then when we restart the server after placing some new blocks the server has some problems : 
- the server doesn't terminate it starting state
- spam in logs 
- to stop the server I have to kill it, if I stop it, nothing happens
- noone can connect because of the starting state
Note that the server is blocking after trying to load a world that could be loaded when ia wasn't installed.
**Minecraft version :** 1.20.2
**Paper version :** This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
**Logs : ** https://pastebin.com/Nk06BP3i

**Comment by Funasitien** [comment]
Same issue happening on my server, but without the block injector plugin...

**Comment by FewerElk** [comment]
I am going to post this issue on the Paper GitHub

**Comment by FewerElk** [comment]
Solution to fix issue gave in the other issue : upgrade to 1.21
