### ISSUE TITLE
Blocks generated by Iris lose texture when neighbouring blocks are broken

### ISSUE THREAD

**Issue by alexey-va** [ItemsAdder/ItemsAdderBlocksInjector#4]
And this happens only with blocks generated with blcok injector.

https://imgur.com/a/rXFWRaA

**Comment by RareMaker50** [comment]
off-topic but is it possible I could get your config for the blocks your adding?

**Comment by alexey-va** [comment]
https://drive.google.com/file/d/1Lkasq_4aNelzBYMwOy-LBDM9ZPzxj0qP/view?usp=sharing

It is pretty much just copy-paste of default ItemsAdder ore for now

**Comment by RareMaker50** [comment]
> https://drive.google.com/file/d/1Lkasq_4aNelzBYMwOy-LBDM9ZPzxj0qP/view?usp=sharing
> 
> It is pretty much just copy-paste of default ItemsAdder ore for now

Oh sorry should've been more specific, I was talking about the iris config where you changed the default one to add custom ores.

**Comment by alexey-va** [comment]
https://drive.google.com/file/d/17orG9Vvvsq5R_hGiIE6OGzo0GaAH0bM7/view?usp=sharing

**Comment by alexey-va** [comment]
Out of bounds error? I had the same thing. I dont exactly understand how I got rid of it... I just increased build height in server.properties to 512, switched to MyWorlds instead of Multiverse and changed iris world in bukkit.yml from "world" to "survival" (so my default world is vanilla world). I have no idea what helped but the OUT OF BOUNDS console spam was gone

**Comment by RareMaker50** [comment]
oh alright, are you using slimefun ores or itemsadder ores? because for me whenever I try do itemsadder ores it shows the out of bounds error and it generates a corrupt world

**Comment by alexey-va** [comment]
I use ItemsAdder ores which I later convert into slimefun ones via script. It is just a namespace. Try removing iris world from bukkit.yml and create world with /iris create. It solved the problem for me

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, maybe there is another plugin interfering
