### ISSUE TITLE
Namespace changed

### ISSUE THREAD

**Issue by MillionthOdin16** [ItemsAdder/ItemsAdderBlocksInjector#5]
Example is outdated. Example of proper use:

      "minHeight": 1,
      "maxPerChunk": 21,
      "maxHeight": 80,
      "minPerChunk": 7,
      "minSize": 3,
      "maxSize": 7,
      "palette": [{ "block": "iasurvival:cassiterite_ore" }],
      "varience": 7

**Comment by LoneDev6** [comment]
Can you elaborate more please?
Thanks

**Comment by MillionthOdin16** [comment]
The documentation for using an itemsadder ore in iris says the format should be itemsadder:ore_name but that throws errors. The correct format is iasurvival:ore_name like above.

**Comment by LoneDev6** [comment]
Thanks a lot, the default files changed recently.
I fixed the docs
