### ISSUE TITLE
Updating custom blocks makes them just noteblocks

### ISSUE THREAD

**Issue by Zemenus** [ItemsAdder/ItemsAdderBlocksInjector#6]
Problem:
Ok, so, when you trying to make IA blocks generating trough biome settings like for example if you replace deepslate in amethyst caves in overworld pack with custom block - just noteblocks will generate.

But! If you add custom block to the dimension - it generates your custom blocks... well... almost. It generates only the noteblocks with texture of your custom block, but when you update these blocks they would just transform into noteblocks (similar to this guy's problem: https://github.com/VolmitSoftware/Iris/issues/870)

By the way I got ItemsAdder of verison 3.2.5-r3 and BlocksInjector 0.0.6

Minecraft Version:
1.19.2

Iris Version:
2.3.8

Logs:
https://pastebin.com/uihYjrM6

**Comment by LoneDev6** [comment]
I sincerely have no idea, the plugin worked fine last time I tested with Iris.
I see no reason for it to revert blocks

**Comment by Zemenus** [comment]
> I sincerely have no idea, the plugin worked fine last time I tested with Iris. I see no reason for it to revert blocks

I can wait for the fixes. I know that you have a lot of stuff with main itemsadder plugin, so yeah, I'll just wait

**Comment by Zemenus** [comment]
@LoneDev6 Yeahhh... just tested it with latest ItemsAdder (beta r9) - it doesn't work at all. It just generates NoteBlocks if I insert my custom block into biome for example, but if I insert my custom block into dimension - it crashes my server :c

**Comment by adamk523** [comment]
I didn't even get that far, see my Discord post here: [https://discord.com/channels/533407895010803753/1046513541974343782/1046513541974343782](https://discord.com/channels/533407895010803753/1046513541974343782/1046513541974343782)

**Comment by LoneDev6** [comment]
I have an idea of what could be the cause, seems a 1.19.2 recent change.
I'll work on something this week

**Comment by Zemenus** [comment]
> I have an idea of what could be the cause, seems a 1.19.2 recent change. I'll work on something this week

Oh that's very good!

**Comment by adamk523** [comment]
Thanks for the reply LoneDev, looking forward to it!
