### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Kuzmaniac** [ItemsAdder/ItemsAdderBlocksInjector#7]
Hello ItemsAdder team,
First of all, thank you for this great plugin!

but there is a problem with the ItemsAdderBlockInjector extension. When I install it, my server shuts down, I really don't know what could be the reason. I downloaded all requested plugins and also iris works perfectly.

**Comment by LoneDev6** [comment]
please post your complete log

**Comment by Kuzmaniac** [comment]
[latest.log](https://github.com/ItemsAdder/ItemsAdderBlocksInjector/files/10511346/latest.log)

**Comment by Kuzmaniac** [comment]
I use the plugins:
ItemsAdderBlocksInjector 0.0.7
ItemsAdder_3.3.0b-r5
ViaVersion-4.5.1
Iris-2.3.13-1.19.3

**Comment by Kuzmaniac** [comment]
The Server Version is Paper 1.19.3

**Comment by LoneDev6** [comment]
Why was this issue closed?

**Comment by Kuzmaniac** [comment]
I put the server on 1.19.2 and then everything worked
but now I have another problem
-> https://github.com/ItemsAdder/ItemsAdderBlocksInjector/issues/8
