### ISSUE TITLE
1.19.3 is not available / supported

### ISSUE THREAD

**Issue by bowencraft** [ItemsAdder/ItemsAdderBlocksInjector#9]
I am using 1.19.3 paper server with only itemsadder, iris, itemsadderblockinjector and their required dependencies installed.
When I install blockinjector, the plugin does not load properly and the server closes automatically after startup.

Here is the plugin list:
- ProtocolLib
- Iris-2.3.13-1.19.3
- ViaVersion-4.5.1
- itemsadder-blocks-injector_0.0.7
- ItemsAdder_3.3.1
- LoneLibs

And here is the server log:
[latest.log](https://github.com/ItemsAdder/ItemsAdderBlocksInjector/files/10678301/latest.log)

**Comment by Kuzmaniac** [comment]
Same problem on 1.19.3

**Comment by LoneDev6** [comment]
Thanks, this will be updated as soon as possible

**Comment by Kuzmaniac** [comment]
great. thank you!

**Comment by LoneDev6** [comment]
https://github.com/ItemsAdder/ItemsAdderBlocksInjector/releases/tag/0.0.8
